// src/lib/countries.ts

export interface Country {
  name: string;
  flag: string;
  code: string;
}

export const countries: Country[] = [
  { name: "United Kingdom", flag: "🇬🇧", code: "GB" },
  { name: "United States", flag: "🇺🇸", code: "US" },
  { name: "Canada", flag: "🇨🇦", code: "CA" },
  { name: "Australia", flag: "🇦🇺", code: "AU" },
  { name: "Germany", flag: "🇩🇪", code: "DE" },
  { name: "France", flag: "🇫🇷", code: "FR" },
  { name: "India", flag: "🇮🇳", code: "IN" },
  { name: "China", flag: "🇨🇳", code: "CN" },
  { name: "Japan", flag: "🇯🇵", code: "JP" },
  { name: "Afghanistan", flag: "🇦🇫", code: "AF" },
  { name: "Albania", flag: "🇦🇱", code: "AL" },
  { name: "Algeria", flag: "🇩🇿", code: "DZ" },
  { name: "Andorra", flag: "🇦🇩", code: "AD" },
  { name: "Angola", flag: "🇦🇴", code: "AO" },
  { name: "Argentina", flag: "🇦🇷", code: "AR" },
  { name: "Armenia", flag: "🇦🇲", code: "AM" },
  { name: "Austria", flag: "🇦🇹", code: "AT" },
  { name: "Azerbaijan", flag: "🇦🇿", code: "AZ" },
  { name: "Bahrain", flag: "🇧🇭", code: "BH" },
  { name: "Bangladesh", flag: "🇧🇩", code: "BD" },
  { name: "Belarus", flag: "🇧🇾", code: "BY" },
  { name: "Belgium", flag: "🇧🇪", code: "BE" },
  { name: "Belize", flag: "🇧🇿", code: "BZ" },
  { name: "Benin", flag: "🇧🇯", code: "BJ" },
  { name: "Bhutan", flag: "🇧🇹", code: "BT" },
  { name: "Bolivia", flag: "🇧🇴", code: "BO" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BA" },
  { name: "Botswana", flag: "🇧🇼", code: "BW" },
  { name: "Brazil", flag: "🇧🇷", code: "BR" },
  { name: "Bulgaria", flag: "🇧🇬", code: "BG" },
  { name: "Burkina Faso", flag: "🇧🇫", code: "BF" },
  { name: "Burundi", flag: "🇧🇮", code: "BI" },
  { name: "Cambodia", flag: "🇰🇭", code: "KH" },
  { name: "Cameroon", flag: "🇨🇲", code: "CM" },
  { name: "Chile", flag: "🇨🇱", code: "CL" },
  { name: "Colombia", flag: "🇨🇴", code: "CO" },
  { name: "Costa Rica", flag: "🇨🇷", code: "CR" },
  { name: "Croatia", flag: "🇭🇷", code: "HR" },
  { name: "Cuba", flag: "🇨🇺", code: "CU" },
  { name: "Cyprus", flag: "🇨🇾", code: "CY" },
  { name: "Czech Republic", flag: "🇨🇿", code: "CZ" },
  { name: "Denmark", flag: "🇩🇰", code: "DK" },
  { name: "Djibouti", flag: "🇩🇯", code: "DJ" },
  { name: "Dominican Republic", flag: "🇩🇴", code: "DO" },
  { name: "Ecuador", flag: "🇪🇨", code: "EC" },
  { name: "Egypt", flag: "🇪🇬", code: "EG" },
  { name: "El Salvador", flag: "🇸🇻", code: "SV" },
  { name: "Estonia", flag: "🇪🇪", code: "EE" },
  { name: "Ethiopia", flag: "🇪🇹", code: "ET" },
  { name: "Finland", flag: "🇫🇮", code: "FI" },
  { name: "Georgia", flag: "🇬🇪", code: "GE" },
  { name: "Ghana", flag: "🇬🇭", code: "GH" },
  { name: "Greece", flag: "🇬🇷", code: "GR" },
  { name: "Guatemala", flag: "🇬🇹", code: "GT" },
  { name: "Guinea", flag: "🇬🇳", code: "GN" },
  { name: "Haiti", flag: "🇭🇹", code: "HT" },
  { name: "Honduras", flag: "🇭🇳", code: "HN" },
  { name: "Hong Kong", flag: "🇭🇰", code: "HK" },
  { name: "Hungary", flag: "🇭🇺", code: "HU" },
  { name: "Iceland", flag: "🇮🇸", code: "IS" },
  { name: "Indonesia", flag: "🇮🇩", code: "ID" },
  { name: "Iran", flag: "🇮🇷", code: "IR" },
  { name: "Iraq", flag: "🇮🇶", code: "IQ" },
  { name: "Ireland", flag: "🇮🇪", code: "IE" },
  { name: "Israel", flag: "🇮🇱", code: "IL" },
  { name: "Italy", flag: "🇮🇹", code: "IT" },
  { name: "Jamaica", flag: "🇯🇲", code: "JM" },
  { name: "Jordan", flag: "🇯🇴", code: "JO" },
  { name: "Kazakhstan", flag: "🇰🇿", code: "KZ" },
  { name: "Kenya", flag: "🇰🇪", code: "KE" },
  { name: "Kuwait", flag: "🇰🇼", code: "KW" },
  { name: "Kyrgyzstan", flag: "🇰🇬", code: "KG" },
  { name: "Latvia", flag: "🇱🇻", code: "LV" },
  { name: "Lebanon", flag: "🇱🇧", code: "LB" },
  { name: "Libya", flag: "🇱🇾", code: "LY" },
  { name: "Liechtenstein", flag: "🇱🇮", code: "LI" },
  { name: "Lithuania", flag: "🇱🇹", code: "LT" },
  { name: "Luxembourg", flag: "🇱🇺", code: "LU" },
  { name: "Malaysia", flag: "🇲🇾", code: "MY" },
  { name: "Maldives", flag: "🇲🇻", code: "MV" },
  { name: "Malta", flag: "🇲🇹", code: "MT" },
  { name: "Mexico", flag: "🇲🇽", code: "MX" },
  { name: "Monaco", flag: "🇲🇨", code: "MC" },
  { name: "Mongolia", flag: "🇲🇳", code: "MN" },
  { name: "Montenegro", flag: "🇲🇪", code: "ME" },
  { name: "Morocco", flag: "🇲🇦", code: "MA" },
  { name: "Nepal", flag: "🇳🇵", code: "NP" },
  { name: "Netherlands", flag: "🇳🇱", code: "NL" },
  { name: "New Zealand", flag: "🇳🇿", code: "NZ" },
  { name: "Nigeria", flag: "🇳🇬", code: "NG" },
  { name: "North Korea", flag: "🇰🇵", code: "KP" },
  { name: "Norway", flag: "🇳🇴", code: "NO" },
  { name: "Oman", flag: "🇴🇲", code: "OM" },
  { name: "Pakistan", flag: "🇵🇰", code: "PK" },
  { name: "Panama", flag: "🇵🇦", code: "PA" },
  { name: "Paraguay", flag: "🇵🇾", code: "PY" },
  { name: "Peru", flag: "🇵🇪", code: "PE" },
  { name: "Philippines", flag: "🇵🇭", code: "PH" },
  { name: "Poland", flag: "🇵🇱", code: "PL" },
  { name: "Portugal", flag: "🇵🇹", code: "PT" },
  { name: "Qatar", flag: "🇶🇦", code: "QA" },
  { name: "Romania", flag: "🇷🇴", code: "RO" },
  { name: "Russia", flag: "🇷🇺", code: "RU" },
  { name: "Saudi Arabia", flag: "🇸🇦", code: "SA" },
  { name: "Serbia", flag: "🇷🇸", code: "RS" },
  { name: "Singapore", flag: "🇸🇬", code: "SG" },
  { name: "Slovakia", flag: "🇸🇰", code: "SK" },
  { name: "Slovenia", flag: "🇸🇮", code: "SI" },
  { name: "South Africa", flag: "🇿🇦", code: "ZA" },
  { name: "South Korea", flag: "🇰🇷", code: "KR" },
  { name: "Spain", flag: "🇪🇸", code: "ES" },
  { name: "Sri Lanka", flag: "🇱🇰", code: "LK" },
  { name: "Sweden", flag: "🇸🇪", code: "SE" },
  { name: "Switzerland", flag: "🇨🇭", code: "CH" },
  { name: "Taiwan", flag: "🇹🇼", code: "TW" },
  { name: "Tajikistan", flag: "🇹🇯", code: "TJ" },
  { name: "Tanzania", flag: "🇹🇿", code: "TZ" },
  { name: "Thailand", flag: "🇹🇭", code: "TH" },
  { name: "Tunisia", flag: "🇹🇳", code: "TN" },
  { name: "Turkey", flag: "🇹🇷", code: "TR" },
  { name: "Turkmenistan", flag: "🇹🇲", code: "TM" },
  { name: "Uganda", flag: "🇺🇬", code: "UG" },
  { name: "Ukraine", flag: "🇺🇦", code: "UA" },
  { name: "United Arab Emirates", flag: "🇦🇪", code: "AE" },
  { name: "Uruguay", flag: "🇺🇾", code: "UY" },
  { name: "Uzbekistan", flag: "🇺🇿", code: "UZ" },
  { name: "Venezuela", flag: "🇻🇪", code: "VE" },
  { name: "Vietnam", flag: "🇻🇳", code: "VN" },
  { name: "Yemen", flag: "🇾🇪", code: "YE" },
  { name: "Zambia", flag: "🇿🇲", code: "ZM" },
  { name: "Zimbabwe", flag: "🇿🇼", code: "ZW" },
];