export interface SkuData {
  sku: string;
  category: string;
}

export const productSkus: Record<string, SkuData> = {
  "dell-14-latitude-7420-2-in-1-touchscreen-rgrw0": { sku: "RGRW0", category: "Computers & Laptops, Dell, Laptop" },
  "dell-latitude-5540-15-6-intel-core-i5-1345u-yryyw": { sku: "YRYYW", category: "Dell, Dell Laptop" },
  "dell-latitude-5540-15-6-intel-core-i7-1365u-tpjj4": { sku: "TPJJ4", category: "Dell, Dell Laptop" },
  "dell-15-6-latitude-5540-notebook-x3vh2": { sku: "X3VH2", category: "Dell, Dell Laptop" },
  "dell-wd19s-docking-station-usb-c": { sku: "210", category: "Computers & Laptops, Dell, Dell Docking Station" },
  "dell-6-in-1-multiport-adapter-da305u": { sku: "DELL-DA305U", category: "Computers & Laptops, Dell, Dell Docking Station" },
  "dell-performance-docking-station-wd19s": { sku: "DELL-WD19DCS", category: "Dell, Dell Docking Station" },
  "dell-wd19s-docking-station-150w": { sku: "DELL-WD19S130W", category: "Dell, Dell Docking Station" },
  "dell-thunderbolt-dock-wd22tb4": { sku: "DELL-WD22TB4", category: "Dell, Dell Docking Station" },
  "dell-wd19s-docking-station-usb-c-210w": { sku: "210-AZBG", category: "Computers & Laptops, Dell, Dell Docking Station" },
  "dell-wired-usb-3-2-gen-2-dell-wd19s180w": { sku: "DELL-WD19S180W", category: "Dell, Dell Docking Station" },
  "dell-optiplex-7010-intel-core-i5-7k8h1": { sku: "7K8H1", category: "Dell, Dell Workstation, Workstations" },
  "dell-optiplex-7010-intel-core-i5-9cvpx": { sku: "9CVPX", category: "Dell, Dell Workstation, Workstations" },
  "dell-optiplex-plus-7410-intel-core-i5-hj6vr": { sku: "HJ6VR", category: "Dell, Dell Workstation, Workstations" },
  "hp-322pv-21-4-full-hd-led-monitor": { sku: "9U5A2AA#ABU", category: "HP Displays" },
  "hp-324pf-23-8-fhd-ips-monitor-100hz": { sku: "9U5J5UT#ABU", category: "HP Displays" },
  "hp-324pv-24-full-hd-va-monitor-100hz": { sku: "9U5C1AA#ABU", category: "HP Displays" },
  "hp-524pu-23-8-fhd-ips-monitor-100hz-usb-c": { sku: "9D9V7AA#ABU", category: "HP Displays" },
  "hp-7-pro-24-wuxga-ips-monitor-8x534aa": { sku: "8X534AA#ABU", category: "HP Displays" },
  "hp-p24h-g5-24-fhd-ips-monitor": { sku: "8X530E9#ABU", category: "HP Displays" },
  "hp-p24h-g5-24-full-hd-ips-monitor-75hz": { sku: "8J4D8AA#ABU", category: "HP Displays" },
  "hp-p27-g5-27-fhd-ips-monitor-64x89aa": { sku: "8J9E6E9#ABU", category: "HP Displays" },
  "hp-p27h-g5-27-fhd-ips-monitor-64w41aa": { sku: "8RA46AA", category: "HP Displays" },
  "hp-series-7-pro-24-wuxga-monitor-724pn": { sku: "16U00AA", category: "HP Displays" },
  "hp-e22-g5-22-fhd-ips-monitor-6n4e8aa": { sku: "6N4E8AA#ABU", category: "HP Displays" },
  "hp-e24i-g4-24-ips-monitor-1920x1200": { sku: "9VJ40AA#ABU", category: "HP Displays" },
  "hp-e24mv-g4-24-fhd-ips-webcam-monitor": { sku: "169L0AA#ABU", category: "HP Displays" },
  "hp-e27-g5-27-fhd-ips-monitor-6n4e2aa": { sku: "6N4E2AA#ABU", category: "HP Displays" },
  "hp-e27k-g5-27-4k-uhd-monitor-ips-usb-c": { sku: "6N4C4AA#ABU", category: "HP Displays" },
  "hp-p22-g5-22-fhd-ips-monitor": { sku: "6N4D3AA#ABU", category: "HP Displays" },
  "hp-p22h-g5-22-fhd-ips-monitor": { sku: "678U5AA#ABU", category: "HP Displays" },
  "hp-p22v-g5-22-class-full-hd-lcd-monitor": { sku: "64X86AA#ABU", category: "HP Displays" },
  "hp-e27u-g5-27-qhd-usb-c-monitor": { sku: "64W30AA#ABU", category: "HP Displays" },
  "hp-m24m-24-class-webcam-full-hd-led": { sku: "64V81AA#ABU", category: "HP Displays" },
  "hp-series-7-pro-31-5-4k-thunderbolt-4-monitor": { sku: "64W34AA#ABU", category: "HP Displays" },
  "hp-series-7-pro-37-5-wqhd-thunderbolt-4": { sku: "64W34AA#ABB", category: "HP Displays" },
  "hp-724pf-23-8-fhd-ips-monitor-100hz": { sku: "64X69AA#ABU", category: "HP Displays" },
  "hp-727pq-27-class-wqhd-led-monitor": { sku: "64W41AA#ABU", category: "HP Displays" },
  "hp-727pu-27-wqhd-ips-black-monitor-120hz": { sku: "8X534E9#ABU", category: "HP Displays" },
  "hp-b250-vesa-100x100-mounting-bracket": { sku: "8Y2K9AA#ABU", category: "HP Displays" },
  "hp-b550-mounting-bracket-for-monitor": { sku: "8K167AA#ABU", category: "HP Displays" },
  "hp-usb-c-dock-g5-5tw10aa": { sku: "D9Y32AA#ABA", category: "HP, HP Docking Station" },
  "hp-thunderbolt-dock-g4-280w-4j0a2aa": { sku: "2UK37AA#ABA", category: "HP, HP Docking Station" },
  "hp-usb-c-a-universal-dock-g2-5tw13aa": { sku: "5TW13AA", category: "HP, HP Docking Station" },
  "hp-125-keyboard-cable-connectivity-usb-type": { sku: "266C9AA#ABE", category: "HP Keyboards & Keypads" },
  "hp-125-keyboard-with-usb-cable-connectivity": { sku: "266C9AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-125-wired-usb-keyboard-french": { sku: "266C9AA#ABF", category: "HP Keyboards & Keypads" },
  "hp-225-eco-friendly-wired-keyboard-and-mouse": { sku: "286J4AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-225-keyboard-mouse-usb-cable": { sku: "286J4AA#ABD", category: "HP Keyboards & Keypads" },
  "hp-225-wireless-keyboard-with-numeric": { sku: "805T1AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-235-wireless-keyboard-mouse": { sku: "1Y4D0UT#ABU", category: "HP Keyboards & Keypads" },
  "hp-320mk-keyboard-mouse-english-usb": { sku: "9SR36AA#ABB", category: "HP Keyboards & Keypads" },
  "hp-320mk-usb-wired-keyboard-mouse": { sku: "9SR36AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-405-backlit-wired-keyboard-usb-a-usb": { sku: "7N7C1AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-455-programmable-wl-kbd": { sku: "4R177AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-475-dual-mode-wireless-keyboard-jet": { sku: "7N7B9AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-4b5-keyboard-cable-connectivity-usb-type": { sku: "8T6M2AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-655-keyboard-mouse-usb-type-a": { sku: "4R009AA", category: "HP Keyboards & Keypads" },
  "hp-655-wireless-keyboard-and-mouse": { sku: "4R009AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-685-comfort-dualmode-keyboard": { sku: "8T6L9UT#ABU", category: "HP Keyboards & Keypads" },
  "hp-6b5-keyboard-mouse-english-uk": { sku: "8T6L7UT#ABU", category: "HP Keyboards & Keypads" },
  "hp-725-multi-device-rechargeable-wireless": { sku: "9T5B0UT#ABU", category: "HP Keyboards & Keypads" },
  "hp-950mk-wireless-rechargeable-keyboard": { sku: "3M165AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-975-rugged-keyboard-wireless": { sku: "Z726AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-compact-355-rugged-keyboard-wireless": { sku: "692S9AA#ABU", category: "HP Keyboards & Keypads" },
  "hp-wired-desktop-320k-keyboard-usb": { sku: "", category: "HP Keyboards & Keypads" },
  "hp-14-elitebook-640-g9-6c0z3ut": { sku: "6C0Z3UT", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-14-elitebook-640-g9-6c0z3ut-aba": { sku: "6C0Z3UT#ABA", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-250-g10-39-6-cm-15-6-notebook-16-gb": { sku: "9B9R8EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-250-g10-laptop-intel-i5-16gb-ram-256gb-ssd-full-hd-win-11-pro": { sku: "AK9U4AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-250-g10-laptop-intel-i5-16gb-ram-512gb": { sku: "AK9T1AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-250-g10-laptop-intel-i5-8gb-ram-256gb-ssd-15-6-fhd-win-11-pro": { sku: "AK9T2AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elite-x360-830-g11-convertible-2-in-1": { sku: "9G0S6ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-1040-g11-14-business-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd": { sku: "9G180ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-640-g10-i5-16gb-512gb-ssd-win-11-pro-9y6s0at-abu": { sku: "9Y6S0AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-640-g11-35-6-cm-14-notebook": { sku: "9G1X5ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-640-g11-laptop-16gb-ddr5-ram-and-512gb-ssd": { sku: "A37TLET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-650-g10-powerful-business-laptop-with-intel-i5-16gb-ram-512gb-ssd": { sku: "9Y6S1AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-660-g11-16-notebook": { sku: "A37TMET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-660-g11-16-16gb-ram-512gb-ssd-13-86h-battery": { sku: "A37TNET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-665-g11-laptop-16-wuxga-display-amd-ryzen-7-7735u-16gb-ddr5-512gb-ssd": { sku: "A23G0EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-14-g11-laptop-intel-core-ultra-5-125u-16gb-ddr5-256gb-ssd": { sku: "8A4U4EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-g10-14-business-laptop-i5-1335u-16gb-512gb-ssd-win-11-pro": { sku: "9M4B9AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-g10-powerful-business-laptop-9m4c0at-abu": { sku: "9M4C0AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-g11-14-business-laptop-intel-core-ultra-5-8gb-ram-256gb-ssd": { sku: "9G175ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-g11-14-notebook-ai-powered-performance-for-hybrid-workforces": { sku: "970U1ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-g11-35-6-cm-14-notebook": { sku: "9G179ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-g11-14-business-laptop-intel-ultra-7-16gb-ram-512gb-ssd": { sku: "9G177ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-840-g11-power-security-for-business-9g176et-abu": { sku: "9G176ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-860-g11-40-6-cm-16-notebook": { sku: "9G0N2ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-ultra-g1i-35-6-cm-14-notebook": { sku: "B66TCAT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-ultra-g1i-35-6-cm-14-touchscreen-notebook": { sku: "B66TDAT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-ultra-g1q-35-6-cm-14-touchscreen-notebook": { sku: "A26TMEA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-ultra-g1q8-35-6-cm-14-notebook": { sku: "9M4E9AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-x-flip-g1i-next-gen-ai-pc-power-your-business-with-ai-driven-performance": { sku: "B68RFEA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-elitebook-x-g1i-next-gen-ai-pc-power-efficiency-and-ai-driven-performance-for-modern-business": { sku: "B66TVAT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-pro-x360-435-g10-13-3-2-in-1-laptop-ryzen-5-16gb-ram-512gb-ssd-win-11-pro": { sku: "9M3X7AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-probook-440-g10-14-business-laptop-i5-13th-gen-8gb-ram-256gb-ssd-win-11-pro": { sku: "9V1N6AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-probook-440-g10-14-business-laptop-i5-1334u-16gb-ram-256gb-ssd-win-11-pro": { sku: "9V1N5AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-probook-440-g11-14-business-laptop-with-intel-ultra-5-16gb-ram-256gb-ssd": { sku: "A37TQET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-probook-450-g10-15-6-notebook-intel-core-i5-1334u-16gb-ram-256gb-ssd-windows-11-pro-pike-silver": { sku: "9V1N8AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-probook-455-g10-39-6-cm-15-6-notebook-9y6r9at-abu": { sku: "9Y6R9AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-probook-460-g11-laptop-16-wuxga-display-intel-core-ultra-5-16gb-ddr5-256gb-ssd": { sku: "A37TRET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-firefly-g11-14-mobile-workstation-a3zd3et-abu": { sku: "A3ZD3ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-firefly-g11-16-mobile-workstation": { sku: "A3ZD1ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-firefly-g11-40-6-cm-16-mobile-workstation": { sku: "A3ZD2ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-firefly-g11-14-workstation-ultra-7-16gb-1tb-ssd-rtx-a500": { sku: "98N29ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-fury-g11-16-mobile-workstation-ultimate-power-for-professionals-32gb-ram-1tb-ssd-intel-i7-14700hx-rtx-2000-ada": { sku: "98K35ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-fury-g11-16-mobile-workstation-ultimate-power-for-professionals-intel-i9-nvidia-rtx-2000-32gb-ram-1tb-ssd": { sku: "98K67ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-fury-g11-16-mobile-workstation-ultimate-on-the-go-power-for-professionals": { sku: "98K12ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-power-g11-16-mobile-workstation-intel-core-ultra-7-32gb-ram-wuxga-display-eyesafe-wifi-6": { sku: "A3ZD5ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-power-g11-16-mobile-workstation-intel-core-ultra-9-32gb-ram-wuxga-display-eyesafe-webcam": { sku: "A3ZD7ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-power-g11-16-mobile-workstation-intel-ultra-9-32gb-ram-1tb-ssd-rtx-3000-ada-windows-11-pro": { sku: "A3YT2ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-power-g11-40-6-cm-16-mobile-workstation": { sku: "98N73ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-power-g11-ultra-7-32gb-1tb-ssd-rtx-a1000": { sku: "A3YS6ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-studio-g11-16-mobile-workstation-intel-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-2000-ada": { sku: "98L12ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-studio-g11-40-6-cm-16-mobile-workstation": { sku: "98L17ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-zbook-studio-g11-40-6-cm-16-mobile-workstation-2": { sku: "98L14ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "k12-pb455g10-r5-7530u-powerful-laptop-for-education-amd": { sku: "A3YV0ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "pb445g10-r5-7530u-high-performance-laptop-amd": { sku: "AK9N4AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "zbpg11a-r7-8845hs-high-performance-computer-hardware-amd": { sku: "86B20EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "zfly14g11a-r7-8840hs-high-performance-computer-processor-amd": { sku: "AK9U7AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop" },
  "hp-laserjet-pro-m501dn-j8h61a-bgj": { sku: "7KW56A#B19", category: "HP, HP Printer, Printers" },
  "hp-color-laserjet-pro-mfp-m183fw": { sku: "J8H61A#BGJ", category: "HP, HP Printer, Printers" },
  "hp-officejet-200-mobile-printer-j8h61a": { sku: "CZ993A#BHC", category: "HP, HP Printer, Printers" },
  "aruba-2930m-48g-poe-1-slot-managed-l3": { sku: "JL322A", category: "HP Switches, Switches" },
  "aruba-6100-48g-class4-poe-4sfp-370w": { sku: "JL675A", category: "HP Switches, Switches" },
  "aruba-cx-6300m-managed-l3-black": { sku: "JL658A", category: "HP Switches, Switches" },
  "aruba-instant-on-1960-48g-2xgt-2sfp": { sku: "JL808A#ABA", category: "HP Switches, Switches" },
  "aruba-instant-on-1960-48g-40p-class4-8p": { sku: "JL809A#ABA", category: "HP Switches, Switches" },
  "hewlett-packard-enterprise-network-power-supply": { sku: "JL087A", category: "HP Switches, Switches" },
  "hp-2930f-24g-poe-4sfp-managed-l3": { sku: "JL261A", category: "HP Switches, Switches" },
  "hp-2930f-48g-poe-4sfp-switch-fiber-optic": { sku: "JL262A", category: "HP Switches, Switches" },
  "hp-aruba-2930f-48g-poe-4sfp-plus-managed-l3": { sku: "JL256A", category: "HP Switches, Switches" },
  "power-supply-jl088a": { sku: "JL086A", category: "HP Switches, Switches" },
  "hp-pro-290-g9-intel-core-i5-6z3w1et": { sku: "623W1ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-pro-400-g9-intel-core-i5": { sku: "623W9ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-tower-windows-11-pro-core-i9-14th-gen": { sku: "996Y7ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z1-g9-desktop-computer-intel-core-i9": { sku: "996V8ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-g9-workstation-core-i7-14th-gen": { sku: "996Y3ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-g9-workstation-i7-14700-16gb": { sku: "8T1R4EA#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-g9-workstation-i7-14700-32gb": { sku: "996Y2ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-g9-workstation-intel-i7-14700": { sku: "996V7ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-g9-workstation-intel-i7-14700k": { sku: "996V4ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-g9-workstation-intel-i9-14900k-rtx": { sku: "8T1K6EA#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-g9-workstation-intel-w680-chip": { sku: "996V6ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-mini-g9-workstation-1-core-i7": { sku: "996W9ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-mini-g9-workstation-compact": { sku: "996N7ET#ABU", category: "HP, HP Workstation, Workstations" },
  "hp-z2-mini-g9-workstation-i9-14900k": { sku: "996T0ET#ABU", category: "HP, HP Workstation, Workstations" },
  "lenovo-thinkpad-universal-usb-c-dock-40ay0090us": { sku: "40AY0090US", category: "Computers & Laptops, Lenovo, Lenovo Docking Station" },
  "lenovo-thinkpad-ultra-docking-station": { sku: "40AJ0135US", category: "Computers & Laptops, Lenovo, Lenovo Docking Station" },
  "lenovo-thinkpad-hybrid-usb-c-with-usb-a-dock": { sku: "40AF0135US", category: "Computers & Laptops, Lenovo, Lenovo Docking Station" },
  "lenovo-thinkstation-p3-tiny-workstation": { sku: "11VL001MUK", category: "Lenovo, Lenovo Workstation" },
  "lenovo-thinkcentre-m75s-gen-2-11r8002quk": { sku: "11R8002QUK", category: "Lenovo, Lenovo Workstation" },
  "lenovo-100e-chromebook-gen-4-82w00003uk-29-5-cm-11-6-chromebook": { sku: "82W00003UK", category: "Lenovo Laptop" },
  "lenovo-14-privacy-screen-filter-blue-light-reduction-nano-technology-heat-humidity-resistant": { sku: "4XJ1M77973", category: "Lenovo Laptop" },
  "lenovo-14-privacy-screen-filter-16-10-for-x1-yoga-gen6-anti-glare-blue-light-reduction-3m-nanolouvre-tech": { sku: "4XJ1M77972", category: "Lenovo Laptop" },
  "lenovo-14e-chromebook-gen-3-14-full-hd-intel-n200-8gb-ram-128gb-storage": { sku: "82W60006UK", category: "Lenovo Laptop" },
  "lenovo-300w-yoga-gen-4-2-in-1-convertible-laptop-11-6-touchscreen-intel-n100-8gb-ram-128gb-ssd-windows-11-pro": { sku: "82VM000BUK", category: "Lenovo Laptop" },
  "lenovo-500e-yoga-chromebook-gen-4-12-2-wuxga-touchscreen-2-in-1-convertible-intel-n100-8gb-ram-64gb-flash-chromeos": { sku: "82W4000JUK", category: "Lenovo Laptop" },
  "lenovo-privacy-screen-filter-for-33-8-cm-13-3-widescreen-lcd-2-in-1-notebook-16-10": { sku: "4XJ1K79629", category: "Lenovo Laptop" },
  "lenovo-tab-k11-lte-enhanced-edition-11-wuxga-display-mediatek-g88-4gb-ram-128gb-storage-4g-lte-android-13-tablet": { sku: "ZADL0023GB", category: "Lenovo Laptop" },
  "lenovo-tab-k11-lte-enhanced-edition-11-wuxga-display-mediatek-helio-g88-4gb-ram-128gb-storage": { sku: "ZADK0001GB", category: "Lenovo Laptop" },
  "lenovo-tab-k11-lte-enhanced-edition-11-wuxga-display-mediatek-helio-g88-8gb-ram-128gb-storage": { sku: "ZADK0093GB", category: "Lenovo Laptop" },
  "lenovo-thinkbook-14-g7-iml-14-wuxga-laptop-with-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21MR004BUK", category: "Lenovo Laptop" },
  "lenovo-thinkbook-16-g6-abp-16-amd-ryzen-5-business-laptop-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21KK007TUK", category: "Lenovo Laptop" },
  "lenovo-thinkbook-16-g6-abp-laptop-amd-ryzen-7-16gb-ram-512gb-ssd-16-wuxga-display-windows-11-pro": { sku: "21KK002LUK", category: "Lenovo Laptop" },
  "lenovo-thinkbook-16-g7-iml-21ms005guk-16-wuxga-ips-laptop-intel-core-ultra-5-16gb-ram-256gb-ssd-windows-11-pro": { sku: "21MS005GUK", category: "Lenovo Laptop" },
  "lenovo-thinkbook-16-g7-iml-21ms0049uk-16-wuxga-intel-core-ultra-7-16gb-ram-512gb-ssd-intel-arc-graphics-windows-11-pro": { sku: "21MS0049UK", category: "Lenovo Laptop" },
  "lenovo-thinkbook-16-g7-qoy-21nh0004uk-16-wuxga-business-laptop-with-qualcomm-snapdragon-x1p-16gb-ram-512gb-ssd-and-windows-11-pro": { sku: "21NH0004UK", category: "Lenovo Laptop" },
  "lenovo-thinkbook-16p-g5-irx-16-laptop-intel-core-i7-14th-gen-32gb-ram-1tb-ssd-nvidia-geforce-rtx-4060-wqxga-windows-11-pro": { sku: "21N5001AUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-e14-gen-6-21m7002duk-14-wuxga-laptop-intel-core-ultra-5-16gb-ram-256gb-ssd-windows-11-pro": { sku: "21M7002DUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-e16-g1-laptop-16-wuxga-display-16gb-ddr5-ram-512gb-ssd-powerful-business-performance": { sku: "21MA002TUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-e16-gen-2-21ma001wuk-16-wuxga-intel-core-ultra-5-16gb-ram-256gb-ssd-win-11-pro": { sku: "21MA001WUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l13-clam-g5-t-512gb-ssd-16gb-ram": { sku: "21LB0018UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l13-gen-5-13-3-wuxga-ips-laptop-intel-core-ultra-5-125u-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21LB0012UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l13-gen-5-13-3-2-in-1-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd": { sku: "21LM001SUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l13-gen-5-13-3-convertible-2-in-1-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-touchscreen-windows-11-pro": { sku: "21LM001LUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l14-g5-t-ultra-14-wuxga-16gb-ram-512gb-ssd-powerful-business-laptop": { sku: "21L1002VUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l14-gen-5-14-16gb-ram-512gb-ssd-ultra-hd-display": { sku: "21L1003GUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l14-gen-5-14-wuxga-notebook-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21L10039UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l16-g1-t-ultra-16-fhd-business-laptop-16gb-ram-512gb-ssd": { sku: "21L30030UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-l16-gen-1-16-wuxga-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21L3002DUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p1-gen-7-16-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-2000-wqxga-display-windows-11-pro": { sku: "21KV001QUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p1-gen-7-16-laptop-intel-core-ultra-9-32gb-ram-1tb-ssd-nvidia-rtx-2000-wqxga-display-windows-11-pro": { sku: "21KV0021UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p1-gen-7-16-rugged-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-1000-ada-windows-11-pro": { sku: "21KV001PUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p1-gen-7-16-wqxga-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-rtx-4070-windows-11-pro": { sku: "21KV0023UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p1-gen-7-16-wqxga-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-geforce-rtx-4060": { sku: "21KV001SUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p14s-gen-5-ultra-portable-rugged-workstation-64gb-ram-rtx-500-ada-1tb-ssd": { sku: "21G2002HUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p14s-gen-5-14-5-mobile-workstation-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-500-wuxga-display-windows-11-pro": { sku: "21G20009UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p14s-gen-5-mobile-workstation-14-5-wqxga-intel-core-ultra-9-32gb-ram-1tb-ssd-intel-arc-graphics-windows-11-pro": { sku: "21G20030UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p16-gen-2-21fa0005uk-40-6-cm-16-mobile-workstation": { sku: "21FA0005UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p16s-gen-3-16-wuxga-laptop-intel-core-ultra-7-155h-16gb-ddr5-512gb-ssd-rtx-500-ada-4gb-windows-11-pro": { sku: "21KS0006UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p16s-gen-3-21ks0004uk-16-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-500-ada-gen-4gb-windows-11-pro": { sku: "21KS0004UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p16v-gen-2-16-mobile-workstation-intel-core-ultra-9-32gb-ram-1tb-ssd-nvidia-rtx-3000-ada-wuxga-display-windows-11-pro": { sku: "21KX001QUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p16v-gen-2-mobile-workstation-16-wuxga-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-500-ada-windows-11-pro": { sku: "21KX000HUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-p16v-gen-2-mobile-workstation-16-wuxga-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-1000-ada-gen-windows-11-pro": { sku: "21KX000NUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t14-g5-t-ultra-14-wuxga-16gb-ddr5-512gb-ssd-powerful-business-laptop": { sku: "21ML002QUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t14-gen-5-21ml0037uk-14-wuxga-ips-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro-black": { sku: "21ML0037UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t14s-gen-6-14-amd-ryzen-ai-7-pro-32gb-ram-512gb-ssd-windows-11-pro": { sku: "21M10005UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t14s-gen-6-21n10007uk-14-wuxga-laptop-qualcomm-snapdragon-x-elite-32gb-ram-1tb-ssd-windows-11-pro": { sku: "21N10007UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t14s-gen-6-14-rugged-copilot-laptop-qualcomm-snapdragon-x-plus-16gb-ram-512gb-ssd-wuxga-display-windows-11-pro": { sku: "21N10026UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t14s-gen-6-14-touchscreen-rugged-laptop-qualcomm-snapdragon-x-elite-32gb-ram-512gb-ssd-wuxga-display-windows-11-pro": { sku: "21N1000HUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t16-g3-t-ultra-powerful-business-laptop-with-16-display-512gb-ssd-and-16gb-ram": { sku: "21MN004YUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-t16-gen-3-16-wuxga-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21MN004AUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x1-carbon-g12": { sku: "", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x1-carbon-g12-powerful-durable-and-lightweight-14-laptop-with-32gb-ram-1tb-ssd": { sku: "21KC005RUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x1-carbon-gen-12-14-wuxga-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x1-carbon-gen-13-21ns0010uk-14-2-8k-copilot-pc-intel-core-ultra-7-32gb-ram-1tb-ssd-windows-11-pro": { sku: "21NS0010UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x1-gen-9-14-2-in-1-touchscreen-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x1-gen-9-14-touchscreen-2-in-1-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-windows-11-pro": { sku: "21KE002JUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x13-gen-5-13-3-wuxga-intel-core-ultra-5-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21LU0027UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x13-gen-5-13-3-touchscreen-2-in-1-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-wuxga-display-windows-11-pro": { sku: "21LW001EUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x13-gen-5-13-3-touchscreen-2-in-1-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21LW000MUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x13-gen-5-13-3-wuxga-laptop-intel-core-ultra-7-16gb-ram-1tb-ssd-windows-11-pro-ips-display": { sku: "21LU0025UK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x9-14-gen-1-21qa001kuk-14-wuxga-laptop-intel-core-ultra-7-32gb-ram-512gb-ssd-windows-11-pro-grey": { sku: "21QA001KUK", category: "Lenovo Laptop" },
  "lenovo-thinkpad-x9-14-gen-1-rugged-copilot-laptop-14-wuxga-display-intel-core-ultra-7-32gb-ram-1tb-ssd": { sku: "21QA001WUK", category: "Lenovo Laptop" },
  "lenovo-v15-g4-amn-ryzen-5-82yu00u8uk-powerful-business-laptop-amd": { sku: "", category: "Lenovo Laptop" },
  "lenovo-v15-g4-iru-15-6-full-hd-laptop-intel-core-i5-13420h-8gb-ram-256gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop" },
  "lenovo-v15-g4-iru-83a1008yuk-15-6-full-hd-laptop-intel-core-i5-13th-gen-8gb-ram-512gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop" },
  "lenovo-v15-g4-iru-83a100h9uk-39-6-cm-15-6-notebook-full-hd": { sku: "", category: "Lenovo Laptop" },
  "lenovo-v15-g4-iru-83a100pnuk-15-6-notebook-intel-core-i5-13th-gen-8gb-ram-512gb-ssd-full-hd-windows-11": { sku: "", category: "Lenovo Laptop" },
  "thinkbook-16-g7-arp-laptop-amd-r5-7535hs-16gb-ram-512gb-ssd-wuxga-display": { sku: "21M3002AUK", category: "Lenovo Laptop" },
  "thinkpad-14-laptop-32gb-ram-1tb-ssd-1920x1200-display-for-seamless-performance-and-storage": { sku: "21LS002UUK", category: "Lenovo Laptop" },
  "ThinkPad L14 G5 AMD R7P-7735U | Business Laptop | AMD": { sku: "21L7001BUK", category: "Lenovo Laptop" },
  "thinkpad-l16-g1-amd-r7p-7735u-16-inch-laptop-32gb-ram-1tb-ssd-nvidia-rtx-a1000-high-performance-reliability": { sku: "21FE000LUK", category: "Lenovo Laptop" },
  "thinkpad-p16v1-r9-p7940hs-high-performance-laptop-with-32gb-ram-1tb-ssd-nvidia-rtx-2000-windows-11-pro": { sku: "21FE000XUK", category: "Lenovo Laptop" },
  "thinkpad-series-14-wuxga-r5-7530u-powerful-laptop-amd": { sku: "21ME0004UK", category: "Lenovo Laptop" },
  "thinkpad-t16-series-t16g2a-r7-p7840u-high-performance-laptop-16gb-ram-512gb-ssd": { sku: "21L70017UK", category: "Lenovo Laptop" },
  "tp-e14-amd-g6-t-r7-7735hs-16gb-powerful-laptop-amd": { sku: "", category: "Lenovo Laptop" },
  "tp-e16-amd-g2-laptop-with-r5-7535hs-processor-16gb-ram-512gb-ssd-16-display": { sku: "21M50029UK", category: "Lenovo Laptop" },
  "d-link-dwa-x1850-ax1800-wi-fi-6-usb-adapter": { sku: "DWA-X1850", category: "D-Link" },
  "d-link-dap-x2850-nuclias-connect-ax3600-wi-fi-6-poe-access-point": { sku: "DAP-X2850", category: "D-Link" },
  "ubiquiti-networks-unifi-5-x-switch-8-managed-gigabit": { sku: "US-8-60W-5", category: "Ubiquiti" },
  "ubiquiti-networks-ua-sk-eu-security-access-control-system-white": { sku: "UA-SK-EU", category: "Ubiquiti" },
  "ubiquiti-amplifi-afi-hd-uk-mesh-whole-home-wifi-router-system": { sku: "AFI-HD-UK", category: "Ubiquiti" },
  "lexmark-cx730de-laser-a4-1200-x-1200-dpi-40-ppm": { sku: "47C9593", category: "Lexmark" },
  "acer-predator-um-kx3ee-p08-led-display": { sku: "UM.KX3EE.P08", category: "Acer" },
  "apple-magic-keyboard-for-ipad-pro": { sku: "MWR53B/A", category: "Apple" },
  "ubiquiti-unifi-switch-ultra-210w": { sku: "", category: "" },
  "ubiquiti-unifi-switch-pro-max-24": { sku: "", category: "" },
  "ubiquiti-unifi-switch-usw-enterprise-24-poe": { sku: "", category: "" },
  "ubiquiti-unifi-u6": { sku: "U6-Plus", category: "ubiquiti, Access Point" },
  "ubiquiti-nanobeam-ac-gen2-nbe-5ac-gen2": { sku: "", category: "" },
  "brother-hl-l6410dw-laser-printer-1200-dpi-wi-fi-duplex-printing": { sku: "HLL6210DSKU1", category: "Brother, Printers" },
  "apc-smart-ups-on-line-uninterruptible-power-supply-ups-srt5kxli": { sku: "SRT5KXLI", category: "APC, UPS" },
  "ubiquiti-unifi-nanohd-1733-mbit-s-uap-nanohd-us": { sku: "UAP-NANOHD-US", category: "Ubiquiti, Ubiquiti Access Point" },
  "mikrotik-css106-1g-4p-1s-network-switch": { sku: "", category: "Mikrotik" },
  "dell-x-series-x1026p-managed": { sku: "210-AEIN", category: "Dell" },
  "netgear-26-port-poe-gigabit-ethernet-gs724tpp-100nas": { sku: "GS724TPP-100NAS", category: "Netgear, Netgear Switches, Switches" },
  "brother-ql-810w-label-printer": { sku: "QL810WZU1", category: "Brother" },
  "brother-rj-4250wb-rugged-mobile-label-receipt-printer-rj4250wbz1": { sku: "", category: "" },
  // In src/lib/sku-data.ts inside the productSkus object:

  "brother-ads-2400n-scanner": { sku: "ADS2400NZU1 ", category: "Brother, Scanners" },
  "switch-smart-managed-layer2-5-port": { sku: "USW-FLEX-2.5G-5 ", category: "Ubiquiti, Ubiquiti Switches " },
  "ubiquiti-unifi-dream-machine-pro-managed-gigabit-udm-pro": { sku: " UDM-PRO ", category: "Ubiquiti, Ubiquiti Switches" },
  "ubiquiti-edgerouter-6p-wired-router-gigabit-ethernet-er-6p": { sku: " ER-6P", category: " Routers, Ubiquiti, Ubiquiti Router" },
};