// src/lib/sku-data.ts

export interface SkuData {
  sku: string;
  category: string;
  price: string | number;
  availability?: string; // Field for In Stock / Out of Stock status
}

export const productSkus: Record<string, SkuData> = {
  // --- Dell Laptops ---
  "dell-14-latitude-7420-2-in-1-touchscreen-rgrw0": { 
    sku: "RGRW0", 
    category: "Computers & Laptops, Dell, Laptop", 
    price: "Get a Quote",
    availability: "in stock"
  },
  "dell-latitude-5540-15-6-intel-core-i5-1345u-yryyw": { 
    sku: "YRYYW", 
    category: "Dell, Dell Laptop", 
    price:"Get a Quote",
    availability: ""
  },
  "dell-latitude-5540-15-6-intel-core-i7-1365u-tpjj4": { 
    sku: "TPJJ4", 
    category: "Dell, Dell Laptop", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-15-6-latitude-5540-notebook-x3vh2": { 
    sku: "X3VH2", 
    category: "Dell, Dell Laptop", 
    price: "Get a Quote",
    availability: ""
  },

  // --- Dell Docking Stations ---
  "dell-wd19s-docking-station-usb-c": { 
    sku: "210", 
    category: "Computers & Laptops, Dell, Dell Docking Station", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-6-in-1-multiport-adapter-da305u": { 
    sku: "DELL-DA305U", 
    category: "Computers & Laptops, Dell, Dell Docking Station", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-performance-docking-station-wd19s": { 
    sku: "DELL-WD19DCS", 
    category: "Dell, Dell Docking Station", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-wd19s-docking-station-150w": { 
    sku: "DELL-WD19S130W", 
    category: "Dell, Dell Docking Station", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-thunderbolt-dock-wd22tb4": { 
    sku: "DELL-WD22TB4", 
    category: "Dell, Dell Docking Station", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-wd19s-docking-station-usb-c-210w": { 
    sku: "210-AZBG", 
    category: "Computers & Laptops, Dell, Dell Docking Station", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-wired-usb-3-2-gen-2-dell-wd19s180w": { 
    sku: "DELL-WD19S180W", 
    category: "Dell, Dell Docking Station", 
    price: "Get a Quote",
    availability: ""
  },

  // --- Dell Workstations ---
  "dell-optiplex-7010-intel-core-i5-7k8h1": { 
    sku: "7K8H1", 
    category: "Dell, Dell Workstation, Workstations", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-optiplex-7010-intel-core-i5-9cvpx": { 
    sku: "9CVPX", 
    category: "Dell, Dell Workstation, Workstations", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-optiplex-plus-7410-intel-core-i5-hj6vr": { 
    sku: "HJ6VR", 
    category: "Dell, Dell Workstation, Workstations", 
    price: "Get a Quote",
    availability: ""
  },
  "dell-x-series-x1026p-managed": { 
    sku: "210-AEIN", 
    category: "Dell", 
    price: "Get a Quote",
    availability: ""
  },

  // --- HP Displays ---
  "hp-322pv-21-4-full-hd-led-monitor": { sku: "9U5A2AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-324pf-23-8-fhd-ips-monitor-100hz": { sku: "9U5J5UT#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-324pv-24-full-hd-va-monitor-100hz": { sku: "9U5C1AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-524pu-23-8-fhd-ips-monitor-100hz-usb-c": { sku: "9D9V7AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-7-pro-24-wuxga-ips-monitor-8x534aa": { sku: "8X534AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-p24h-g5-24-fhd-ips-monitor": { sku: "8X530E9#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-p24h-g5-24-full-hd-ips-monitor-75hz": { sku: "8J4D8AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-p27-g5-27-fhd-ips-monitor-64x89aa": { sku: "8J9E6E9#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-p27h-g5-27-fhd-ips-monitor-64w41aa": { sku: "8RA46AA", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-series-7-pro-24-wuxga-monitor-724pn": { sku: "16U00AA", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-e22-g5-22-fhd-ips-monitor-6n4e8aa": { sku: "6N4E8AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-e24i-g4-24-ips-monitor-1920x1200": { sku: "9VJ40AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-e24mv-g4-24-fhd-ips-webcam-monitor": { sku: "169L0AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-e27-g5-27-fhd-ips-monitor-6n4e2aa": { sku: "6N4E2AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-e27k-g5-27-4k-uhd-monitor-ips-usb-c": { sku: "6N4C4AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-p22-g5-22-fhd-ips-monitor": { sku: "6N4D3AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-p22h-g5-22-fhd-ips-monitor": { sku: "678U5AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-p22v-g5-22-class-full-hd-lcd-monitor": { sku: "64X86AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-e27u-g5-27-qhd-usb-c-monitor": { sku: "64W30AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-m24m-24-class-webcam-full-hd-led": { sku: "64V81AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-series-7-pro-31-5-4k-thunderbolt-4-monitor": { sku: "64W34AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-series-7-pro-37-5-wqhd-thunderbolt-4": { sku: "64W34AA#ABB", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-724pf-23-8-fhd-ips-monitor-100hz": { sku: "64X69AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-727pq-27-class-wqhd-led-monitor": { sku: "64W41AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-727pu-27-wqhd-ips-black-monitor-120hz": { sku: "8X534E9#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-b250-vesa-100x100-mounting-bracket": { sku: "8Y2K9AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },
  "hp-b550-mounting-bracket-for-monitor": { sku: "8K167AA#ABU", category: "HP Displays", price: "Get a Quote", availability: "" },

  // --- HP Docking Stations ---
  "hp-usb-c-dock-g5-5tw10aa": { sku: "D9Y32AA#ABA", category: "HP, HP Docking Station", price: "Get a Quote", availability: "" },
  "hp-thunderbolt-dock-g4-280w-4j0a2aa": { sku: "2UK37AA#ABA", category: "HP, HP Docking Station", price: "Get a Quote", availability: "" },
  "hp-usb-c-a-universal-dock-g2-5tw13aa": { sku: "5TW13AA", category: "HP, HP Docking Station", price: "Get a Quote", availability: "" },

  // --- HP Keyboards & Keypads ---
  "hp-125-keyboard-cable-connectivity-usb-type": { sku: "266C9AA#ABE", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-125-keyboard-with-usb-cable-connectivity": { sku: "266C9AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-125-wired-usb-keyboard-french": { sku: "266C9AA#ABF", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-225-eco-friendly-wired-keyboard-and-mouse": { sku: "286J4AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-225-keyboard-mouse-usb-cable": { sku: "286J4AA#ABD", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-225-wireless-keyboard-with-numeric": { sku: "805T1AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-235-wireless-keyboard-mouse": { sku: "1Y4D0UT#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-320mk-keyboard-mouse-english-usb": { sku: "9SR36AA#ABB", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-320mk-usb-wired-keyboard-mouse": { sku: "9SR36AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-405-backlit-wired-keyboard-usb-a-usb": { sku: "7N7C1AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-455-programmable-wl-kbd": { sku: "4R177AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-475-dual-mode-wireless-keyboard-jet": { sku: "7N7B9AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-4b5-keyboard-cable-connectivity-usb-type": { sku: "8T6M2AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-655-keyboard-mouse-usb-type-a": { sku: "4R009AA", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-655-wireless-keyboard-and-mouse": { sku: "4R009AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-685-comfort-dualmode-keyboard": { sku: "8T6L9UT#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-6b5-keyboard-mouse-english-uk": { sku: "8T6L7UT#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-725-multi-device-rechargeable-wireless": { sku: "9T5B0UT#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-950mk-wireless-rechargeable-keyboard": { sku: "3M165AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-975-rugged-keyboard-wireless": { sku: "Z726AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-compact-355-rugged-keyboard-wireless": { sku: "692S9AA#ABU", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },
  "hp-wired-desktop-320k-keyboard-usb": { sku: "", category: "HP Keyboards & Keypads", price: "Get a Quote", availability: "" },

  // --- HP Laptops ---
  "hp-14-elitebook-640-g9-6c0z3ut": { sku: "6C0Z3UT", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-14-elitebook-640-g9-6c0z3ut-aba": { sku: "6C0Z3UT#ABA", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-250-g10-39-6-cm-15-6-notebook-16-gb": { sku: "9B9R8EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-250-g10-laptop-intel-i5-16gb-ram-256gb-ssd-full-hd-win-11-pro": { sku: "AK9U4AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-250-g10-laptop-intel-i5-16gb-ram-512gb": { sku: "AK9T1AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-250-g10-laptop-intel-i5-8gb-ram-256gb-ssd-15-6-fhd-win-11-pro": { sku: "AK9T2AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elite-x360-830-g11-convertible-2-in-1": { sku: "9G0S6ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-1040-g11-14-business-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd": { sku: "9G180ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-640-g10-i5-16gb-512gb-ssd-win-11-pro-9y6s0at-abu": { sku: "9Y6S0AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-640-g11-35-6-cm-14-notebook": { sku: "9G1X5ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-640-g11-laptop-16gb-ddr5-ram-and-512gb-ssd": { sku: "A37TLET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-650-g10-powerful-business-laptop-with-intel-i5-16gb-ram-512gb-ssd": { sku: "9Y6S1AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-660-g11-16-notebook": { sku: "A37TMET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-660-g11-16-16gb-ram-512gb-ssd-13-86h-battery": { sku: "A37TNET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-665-g11-laptop-16-wuxga-display-amd-ryzen-7-7735u-16gb-ddr5-512gb-ssd": { sku: "A23G0EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-14-g11-laptop-intel-core-ultra-5-125u-16gb-ddr5-256gb-ssd": { sku: "8A4U4EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-g10-14-business-laptop-i5-1335u-16gb-512gb-ssd-win-11-pro": { sku: "9M4B9AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-g10-powerful-business-laptop-9m4c0at-abu": { sku: "9M4C0AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-g11-14-business-laptop-intel-core-ultra-5-8gb-ram-256gb-ssd": { sku: "9G175ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-g11-14-notebook-ai-powered-performance-for-hybrid-workforces": { sku: "970U1ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-g11-35-6-cm-14-notebook": { sku: "9G179ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-g11-14-business-laptop-intel-ultra-7-16gb-ram-512gb-ssd": { sku: "9G177ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-840-g11-power-security-for-business-9g176et-abu": { sku: "9G176ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-860-g11-40-6-cm-16-notebook": { sku: "9G0N2ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-ultra-g1i-35-6-cm-14-notebook": { sku: "B66TCAT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-ultra-g1i-35-6-cm-14-touchscreen-notebook": { sku: "B66TDAT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-ultra-g1q-35-6-cm-14-touchscreen-notebook": { sku: "A26TMEA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-ultra-g1q8-35-6-cm-14-notebook": { sku: "9M4E9AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-x-flip-g1i-next-gen-ai-pc-power-your-business-with-ai-driven-performance": { sku: "B68RFEA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-elitebook-x-g1i-next-gen-ai-pc-power-efficiency-and-ai-driven-performance-for-modern-business": { sku: "B66TVAT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-pro-x360-435-g10-13-3-2-in-1-laptop-ryzen-5-16gb-ram-512gb-ssd-win-11-pro": { sku: "9M3X7AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-probook-440-g10-14-business-laptop-i5-13th-gen-8gb-ram-256gb-ssd-win-11-pro": { sku: "9V1N6AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-probook-440-g10-14-business-laptop-i5-1334u-16gb-ram-256gb-ssd-win-11-pro": { sku: "9V1N5AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-probook-440-g11-14-business-laptop-with-intel-ultra-5-16gb-ram-256gb-ssd": { sku: "A37TQET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-probook-450-g10-15-6-notebook-intel-core-i5-1334u-16gb-ram-256gb-ssd-windows-11-pro-pike-silver": { sku: "9V1N8AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-probook-455-g10-39-6-cm-15-6-notebook-9y6r9at-abu": { sku: "9Y6R9AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-probook-460-g11-laptop-16-wuxga-display-intel-core-ultra-5-16gb-ddr5-256gb-ssd": { sku: "A37TRET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-firefly-g11-14-mobile-workstation-a3zd3et-abu": { sku: "A3ZD3ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-firefly-g11-16-mobile-workstation": { sku: "A3ZD1ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-firefly-g11-40-6-cm-16-mobile-workstation": { sku: "A3ZD2ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-firefly-g11-14-workstation-ultra-7-16gb-1tb-ssd-rtx-a500": { sku: "98N29ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-fury-g11-16-mobile-workstation-ultimate-power-for-professionals-32gb-ram-1tb-ssd-intel-i7-14700hx-rtx-2000-ada": { sku: "98K35ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-fury-g11-16-mobile-workstation-ultimate-power-for-professionals-intel-i9-nvidia-rtx-2000-32gb-ram-1tb-ssd": { sku: "98K67ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-fury-g11-16-mobile-workstation-ultimate-on-the-go-power-for-professionals": { sku: "98K12ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-power-g11-16-mobile-workstation-intel-core-ultra-7-32gb-ram-wuxga-display-eyesafe-wifi-6": { sku: "A3ZD5ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-power-g11-16-mobile-workstation-intel-core-ultra-9-32gb-ram-wuxga-display-eyesafe-webcam": { sku: "A3ZD7ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-power-g11-16-mobile-workstation-intel-ultra-9-32gb-ram-1tb-ssd-rtx-3000-ada-windows-11-pro": { sku: "A3YT2ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-power-g11-40-6-cm-16-mobile-workstation": { sku: "98N73ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-power-g11-ultra-7-32gb-1tb-ssd-rtx-a1000": { sku: "A3YS6ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-studio-g11-16-mobile-workstation-intel-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-2000-ada": { sku: "98L12ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-studio-g11-40-6-cm-16-mobile-workstation": { sku: "98L17ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "hp-zbook-studio-g11-40-6-cm-16-mobile-workstation-2": { sku: "98L14ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "k12-pb455g10-r5-7530u-powerful-laptop-for-education-amd": { sku: "A3YV0ET#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "pb445g10-r5-7530u-high-performance-laptop-amd": { sku: "AK9N4AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "zbpg11a-r7-8845hs-high-performance-computer-hardware-amd": { sku: "86B20EA#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },
  "zfly14g11a-r7-8840hs-high-performance-computer-processor-amd": { sku: "AK9U7AT#ABU", category: "Computers & Laptops, HP, HP Laptops, Laptop", price: "Get a Quote", availability: "" },

  // --- HP Printers ---
  "hp-laserjet-pro-m501dn-j8h61a-bgj": { sku: "7KW56A#B19", category: "HP, HP Printer, Printers", price: "Get a Quote", availability: "" },
  "hp-color-laserjet-pro-mfp-m183fw": { sku: "J8H61A#BGJ", category: "HP, HP Printer, Printers", price: "Get a Quote", availability: "" },
  "hp-officejet-200-mobile-printer-j8h61a": { sku: "CZ993A#BHC", category: "HP, HP Printer, Printers", price: "Get a Quote", availability: "" },

  // --- HP Switches ---
  "aruba-2930m-48g-poe-1-slot-managed-l3": { sku: "JL322A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "aruba-6100-48g-class4-poe-4sfp-370w": { sku: "JL675A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "aruba-cx-6300m-managed-l3-black": { sku: "JL658A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "aruba-instant-on-1960-48g-2xgt-2sfp": { sku: "JL808A#ABA", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "aruba-instant-on-1960-48g-40p-class4-8p": { sku: "JL809A#ABA", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "hewlett-packard-enterprise-network-power-supply": { sku: "JL087A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "hp-2930f-24g-poe-4sfp-managed-l3": { sku: "JL261A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "hp-2930f-48g-poe-4sfp-switch-fiber-optic": { sku: "JL262A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "hp-aruba-2930f-48g-poe-4sfp-plus-managed-l3": { sku: "JL256A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },
  "power-supply-jl088a": { sku: "JL086A", category: "HP Switches, Switches", price: "Get a Quote", availability: "" },

  // --- HP Workstations ---
  "hp-pro-290-g9-intel-core-i5-6z3w1et": { sku: "623W1ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-pro-400-g9-intel-core-i5": { sku: "623W9ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-tower-windows-11-pro-core-i9-14th-gen": { sku: "996Y7ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z1-g9-desktop-computer-intel-core-i9": { sku: "996V8ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-g9-workstation-core-i7-14th-gen": { sku: "996Y3ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-g9-workstation-i7-14700-16gb": { sku: "8T1R4EA#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-g9-workstation-i7-14700-32gb": { sku: "996Y2ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-g9-workstation-intel-i7-14700": { sku: "996V7ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-g9-workstation-intel-i7-14700k": { sku: "996V4ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-g9-workstation-intel-i9-14900k-rtx": { sku: "8T1K6EA#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-g9-workstation-intel-w680-chip": { sku: "996V6ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-mini-g9-workstation-1-core-i7": { sku: "996W9ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-mini-g9-workstation-compact": { sku: "996N7ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },
  "hp-z2-mini-g9-workstation-i9-14900k": { sku: "996T0ET#ABU", category: "HP, HP Workstation, Workstations", price: "Get a Quote", availability: "" },

  // --- Lenovo Docking Stations ---
  "lenovo-thinkpad-universal-usb-c-dock-40ay0090us": { sku: "40AY0090US", category: "Computers & Laptops, Lenovo, Lenovo Docking Station", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-ultra-docking-station": { sku: "40AJ0135US", category: "Computers & Laptops, Lenovo, Lenovo Docking Station", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-hybrid-usb-c-with-usb-a-dock": { sku: "40AF0135US", category: "Computers & Laptops, Lenovo, Lenovo Docking Station", price: "Get a Quote", availability: "" },

  // --- Lenovo Workstations ---
  "lenovo-thinkstation-p3-tiny-workstation": { sku: "11VL001MUK", category: "Lenovo, Lenovo Workstation", price: "Get a Quote", availability: "" },
  "lenovo-thinkcentre-m75s-gen-2-11r8002quk": { sku: "11R8002QUK", category: "Lenovo, Lenovo Workstation", price: "Get a Quote", availability: "" },

  // --- Lenovo Laptops ---
  "lenovo-100e-chromebook-gen-4-82w00003uk-29-5-cm-11-6-chromebook": { sku: "82W00003UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-14-privacy-screen-filter-blue-light-reduction-nano-technology-heat-humidity-resistant": { sku: "4XJ1M77973", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-14-privacy-screen-filter-16-10-for-x1-yoga-gen6-anti-glare-blue-light-reduction-3m-nanolouvre-tech": { sku: "4XJ1M77972", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-14e-chromebook-gen-3-14-full-hd-intel-n200-8gb-ram-128gb-storage": { sku: "82W60006UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-300w-yoga-gen-4-2-in-1-convertible-laptop-11-6-touchscreen-intel-n100-8gb-ram-128gb-ssd-windows-11-pro": { sku: "82VM000BUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-500e-yoga-chromebook-gen-4-12-2-wuxga-touchscreen-2-in-1-convertible-intel-n100-8gb-ram-64gb-flash-chromeos": { sku: "82W4000JUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-privacy-screen-filter-for-33-8-cm-13-3-widescreen-lcd-2-in-1-notebook-16-10": { sku: "4XJ1K79629", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-tab-k11-lte-enhanced-edition-11-wuxga-display-mediatek-g88-4gb-ram-128gb-storage-4g-lte-android-13-tablet": { sku: "ZADL0023GB", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-tab-k11-lte-enhanced-edition-11-wuxga-display-mediatek-helio-g88-4gb-ram-128gb-storage": { sku: "ZADK0001GB", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-tab-k11-lte-enhanced-edition-11-wuxga-display-mediatek-helio-g88-8gb-ram-128gb-storage": { sku: "ZADK0093GB", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkbook-14-g7-iml-14-wuxga-laptop-with-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21MR004BUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkbook-16-g6-abp-16-amd-ryzen-5-business-laptop-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21KK007TUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkbook-16-g6-abp-laptop-amd-ryzen-7-16gb-ram-512gb-ssd-16-wuxga-display-windows-11-pro": { sku: "21KK002LUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkbook-16-g7-iml-21ms005guk-16-wuxga-ips-laptop-intel-core-ultra-5-16gb-ram-256gb-ssd-windows-11-pro": { sku: "21MS005GUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkbook-16-g7-iml-21ms0049uk-16-wuxga-intel-core-ultra-7-16gb-ram-512gb-ssd-intel-arc-graphics-windows-11-pro": { sku: "21MS0049UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkbook-16-g7-qoy-21nh0004uk-16-wuxga-business-laptop-with-qualcomm-snapdragon-x1p-16gb-ram-512gb-ssd-and-windows-11-pro": { sku: "21NH0004UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkbook-16p-g5-irx-16-laptop-intel-core-i7-14th-gen-32gb-ram-1tb-ssd-nvidia-geforce-rtx-4060-wqxga-windows-11-pro": { sku: "21N5001AUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-e14-gen-6-21m7002duk-14-wuxga-laptop-intel-core-ultra-5-16gb-ram-256gb-ssd-windows-11-pro": { sku: "21M7002DUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-e16-g1-laptop-16-wuxga-display-16gb-ddr5-ram-512gb-ssd-powerful-business-performance": { sku: "21MA002TUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-e16-gen-2-21ma001wuk-16-wuxga-intel-core-ultra-5-16gb-ram-256gb-ssd-win-11-pro": { sku: "21MA001WUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l13-clam-g5-t-512gb-ssd-16gb-ram": { sku: "21LB0018UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l13-gen-5-13-3-wuxga-ips-laptop-intel-core-ultra-5-125u-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21LB0012UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l13-gen-5-13-3-2-in-1-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd": { sku: "21LM001SUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l13-gen-5-13-3-convertible-2-in-1-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-touchscreen-windows-11-pro": { sku: "21LM001LUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l14-g5-t-ultra-14-wuxga-16gb-ram-512gb-ssd-powerful-business-laptop": { sku: "21L1002VUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l14-gen-5-14-16gb-ram-512gb-ssd-ultra-hd-display": { sku: "21L1003GUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l14-gen-5-14-wuxga-notebook-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21L10039UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l16-g1-t-ultra-16-fhd-business-laptop-16gb-ram-512gb-ssd": { sku: "21L30030UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-l16-gen-1-16-wuxga-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21L3002DUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p1-gen-7-16-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-2000-wqxga-display-windows-11-pro": { sku: "21KV001QUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p1-gen-7-16-laptop-intel-core-ultra-9-32gb-ram-1tb-ssd-nvidia-rtx-2000-wqxga-display-windows-11-pro": { sku: "21KV0021UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p1-gen-7-16-rugged-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-1000-ada-windows-11-pro": { sku: "21KV001PUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p1-gen-7-16-wqxga-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-rtx-4070-windows-11-pro": { sku: "21KV0023UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p1-gen-7-16-wqxga-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-geforce-rtx-4060": { sku: "21KV001SUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p14s-gen-5-ultra-portable-rugged-workstation-64gb-ram-rtx-500-ada-1tb-ssd": { sku: "21G2002HUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p14s-gen-5-14-5-mobile-workstation-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-500-wuxga-display-windows-11-pro": { sku: "21G20009UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p14s-gen-5-mobile-workstation-14-5-wqxga-intel-core-ultra-9-32gb-ram-1tb-ssd-intel-arc-graphics-windows-11-pro": { sku: "21G20030UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p16-gen-2-21fa0005uk-40-6-cm-16-mobile-workstation": { sku: "21FA0005UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p16s-gen-3-16-wuxga-laptop-intel-core-ultra-7-155h-16gb-ddr5-512gb-ssd-rtx-500-ada-4gb-windows-11-pro": { sku: "21KS0006UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p16s-gen-3-21ks0004uk-16-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-500-ada-gen-4gb-windows-11-pro": { sku: "21KS0004UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p16v-gen-2-16-mobile-workstation-intel-core-ultra-9-32gb-ram-1tb-ssd-nvidia-rtx-3000-ada-wuxga-display-windows-11-pro": { sku: "21KX001QUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p16v-gen-2-mobile-workstation-16-wuxga-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-500-ada-windows-11-pro": { sku: "21KX000HUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-p16v-gen-2-mobile-workstation-16-wuxga-intel-core-ultra-7-32gb-ram-1tb-ssd-nvidia-rtx-1000-ada-gen-windows-11-pro": { sku: "21KX000NUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t14-g5-t-ultra-14-wuxga-16gb-ddr5-512gb-ssd-powerful-business-laptop": { sku: "21ML002QUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t14-gen-5-21ml0037uk-14-wuxga-ips-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro-black": { sku: "21ML0037UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t14s-gen-6-14-amd-ryzen-ai-7-pro-32gb-ram-512gb-ssd-windows-11-pro": { sku: "21M10005UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t14s-gen-6-21n10007uk-14-wuxga-laptop-qualcomm-snapdragon-x-elite-32gb-ram-1tb-ssd-windows-11-pro": { sku: "21N10007UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t14s-gen-6-14-rugged-copilot-laptop-qualcomm-snapdragon-x-plus-16gb-ram-512gb-ssd-wuxga-display-windows-11-pro": { sku: "21N10026UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t14s-gen-6-14-touchscreen-rugged-laptop-qualcomm-snapdragon-x-elite-32gb-ram-512gb-ssd-wuxga-display-windows-11-pro": { sku: "21N1000HUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t16-g3-t-ultra-powerful-business-laptop-with-16-display-512gb-ssd-and-16gb-ram": { sku: "21MN004YUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-t16-gen-3-16-wuxga-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21MN004AUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x1-carbon-g12": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x1-carbon-g12-powerful-durable-and-lightweight-14-laptop-with-32gb-ram-1tb-ssd": { sku: "21KC005RUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x1-carbon-gen-12-14-wuxga-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x1-carbon-gen-13-21ns0010uk-14-2-8k-copilot-pc-intel-core-ultra-7-32gb-ram-1tb-ssd-windows-11-pro": { sku: "21NS0010UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x1-gen-9-14-2-in-1-touchscreen-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x1-gen-9-14-touchscreen-2-in-1-laptop-intel-core-ultra-7-32gb-ram-1tb-ssd-windows-11-pro": { sku: "21KE002JUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x13-gen-5-13-3-wuxga-intel-core-ultra-5-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21LU0027UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x13-gen-5-13-3-touchscreen-2-in-1-laptop-intel-core-ultra-5-16gb-ram-512gb-ssd-wuxga-display-windows-11-pro": { sku: "21LW001EUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x13-gen-5-13-3-touchscreen-2-in-1-laptop-intel-core-ultra-7-16gb-ram-512gb-ssd-windows-11-pro": { sku: "21LW000MUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x13-gen-5-13-3-wuxga-laptop-intel-core-ultra-7-16gb-ram-1tb-ssd-windows-11-pro-ips-display": { sku: "21LU0025UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x9-14-gen-1-21qa001kuk-14-wuxga-laptop-intel-core-ultra-7-32gb-ram-512gb-ssd-windows-11-pro-grey": { sku: "21QA001KUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-thinkpad-x9-14-gen-1-rugged-copilot-laptop-14-wuxga-display-intel-core-ultra-7-32gb-ram-1tb-ssd": { sku: "21QA001WUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-v15-g4-amn-ryzen-5-82yu00u8uk-powerful-business-laptop-amd": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-v15-g4-iru-15-6-full-hd-laptop-intel-core-i5-13420h-8gb-ram-256gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-v15-g4-iru-83a1008yuk-15-6-full-hd-laptop-intel-core-i5-13th-gen-8gb-ram-512gb-ssd-windows-11-pro": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-v15-g4-iru-83a100h9uk-39-6-cm-15-6-notebook-full-hd": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "lenovo-v15-g4-iru-83a100pnuk-15-6-notebook-intel-core-i5-13th-gen-8gb-ram-512gb-ssd-full-hd-windows-11": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "thinkbook-16-g7-arp-laptop-amd-r5-7535hs-16gb-ram-512gb-ssd-wuxga-display": { sku: "21M3002AUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "thinkpad-14-laptop-32gb-ram-1tb-ssd-1920x1200-display-for-seamless-performance-and-storage": { sku: "21LS002UUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "ThinkPad L14 G5 AMD R7P-7735U | Business Laptop | AMD": { sku: "21L7001BUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "thinkpad-l16-g1-amd-r7p-7735u-16-inch-laptop-32gb-ram-1tb-ssd-nvidia-rtx-a1000-high-performance-reliability": { sku: "21FE000LUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "thinkpad-p16v1-r9-p7940hs-high-performance-laptop-with-32gb-ram-1tb-ssd-nvidia-rtx-2000-windows-11-pro": { sku: "21FE000XUK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "thinkpad-series-14-wuxga-r5-7530u-powerful-laptop-amd": { sku: "21ME0004UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "thinkpad-t16-series-t16g2a-r7-p7840u-high-performance-laptop-16gb-ram-512gb-ssd": { sku: "21L70017UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "tp-e14-amd-g6-t-r7-7735hs-16gb-powerful-laptop-amd": { sku: "", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },
  "tp-e16-amd-g2-laptop-with-r5-7535hs-processor-16gb-ram-512gb-ssd-16-display": { sku: "21M50029UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },

  // --- D-Link ---
  "d-link-dwa-x1850-ax1800-wi-fi-6-usb-adapter": { sku: "DWA-X1850", category: "D-Link", price: 200, availability: "" },
  "d-link-dap-x2850-nuclias-connect-ax3600-wi-fi-6-poe-access-point": { sku: "DAP-X2850", category: "D-Link", price: "Get a Quote", availability: "" },

  // --- Ubiquiti ---
  "ubiquiti-networks-unifi-5-x-switch-8-managed-gigabit": { sku: "US-8-60W-5", category: "Ubiquiti", price: "Get a Quote", availability: "" },
  "ubiquiti-networks-ua-sk-eu-security-access-control-system-white": { sku: "UA-SK-EU", category: "Ubiquiti", price: "Get a Quote", availability: "" },
  "ubiquiti-amplifi-afi-hd-uk-mesh-whole-home-wifi-router-system": { sku: "AFI-HD-UK", category: "Ubiquiti", price: "Get a Quote", availability: "" },
  "ubiquiti-unifi-switch-ultra-210w": { sku: "", category: "", price: "Get a Quote", availability: "" },
  "ubiquiti-unifi-switch-pro-max-24": { sku: "", category: "", price: "Get a Quote", availability: "" },
  "ubiquiti-unifi-switch-usw-enterprise-24-poe": { sku: "", category: "", price: "Get a Quote", availability: "" },
  "ubiquiti-unifi-u6": { sku: "U6-Plus", category: "ubiquiti, Access Point", price: "Get a Quote", availability: "" },
  "ubiquiti-nanobeam-ac-gen2-nbe-5ac-gen2": { sku: "", category: "", price: "Get a Quote", availability: "" },
  "ubiquiti-unifi-nanohd-1733-mbit-s-uap-nanohd-us": { sku: "UAP-NANOHD-US", category: "Ubiquiti, Ubiquiti Access Point", price: "Get a Quote", availability: "" },
  "switch-smart-managed-layer2-5-port": { sku: "USW-FLEX-2.5G-5", category: "Ubiquiti, Ubiquiti Switches", price: "Get a Quote", availability: "" },
  "ubiquiti-unifi-dream-machine-pro-managed-gigabit-udm-pro": { sku: "UDM-PRO", category: "Ubiquiti, Ubiquiti Switches", price: "Get a Quote", availability: "" },
  "ubiquiti-edgerouter-6p-wired-router-gigabit-ethernet-er-6p": { sku: "ER-6P", category: "Routers, Ubiquiti, Ubiquiti Router", price: "Get a Quote", availability: "" },

  // --- Lexmark ---
  "lexmark-cx730de-laser-a4-1200-x-1200-dpi-40-ppm": { sku: "47C9593", category: "Lexmark", price: "Get a Quote", availability: "" },

  // --- Acer ---
  "acer-predator-um-kx3ee-p08-led-display": { sku: "UM.KX3EE.P08", category: "Acer", price: "Get a Quote", availability: "" },

  // --- Apple ---
  "apple-magic-keyboard-for-ipad-pro": { sku: "MWR53B/A", category: "Apple", price: "Get a Quote", availability: "" },

  // --- Brother ---
  "brother-hl-l6410dw-laser-printer-1200-dpi-wi-fi-duplex-printing": { sku: "HLL6210DSKU1", category: "Brother, Printers", price: "Get a Quote", availability: "" },
  "brother-ql-810w-label-printer": { sku: "QL810WZU1", category: "Brother", price: "Get a Quote", availability: "" },
  "brother-rj-4250wb-rugged-mobile-label-receipt-printer-rj4250wbz1": { sku: "", category: "", price: "Get a Quote", availability: "" },
  "brother-ads-2400n-scanner": { sku: "ADS2400NZU1", category: "Brother, Scanners", price: "Get a Quote", availability: "" },

  // --- APC ---
  "apc-smart-ups-on-line-uninterruptible-power-supply-ups-srt5kxli": { sku: "SRT5KXLI", category: "APC, UPS", price: "Get a Quote", availability: "" },

  // --- Mikrotik ---
  "mikrotik-css106-1g-4p-1s-network-switch": { sku: "CSS106-1G-4P-1S", category: "Mikrotik", price: "Get a Quote", availability: "" },

  // --- Netgear ---
  "netgear-26-port-poe-gigabit-ethernet-gs724tpp-100nas": { sku: "GS724TPP-100NAS", category: "Netgear, Netgear Switches, Switches", price: "Get a Quote", availability: "" },

  // --- Avaya ---
  "avaya-1403-digital-telephone-700469927": { sku: "700469927", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1416-phone-700469869": { sku: "700469869", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1603sw-ip-phone-700458508": { sku: "700458508", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-9404-digital-telephone-700500204": { sku: "700500204", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-9408-digital-telephone-700500205": { sku: "700500205", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-9504-telset-for-ip-oico": { sku: "700508197", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-9508-ip-phone-charcoal-grey-wired-handset-lcd": { sku: "700500207", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-9601-700506783-sip-ip-phone": { sku: "700506783", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b159-analog-dect-telephone-black": { sku: "700501530", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-h229-trimline-ip-phone-global": { sku: "700514315", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-h239-corded-sip-phone-700513933": { sku: "700513933", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-h249-corded-sip-phone-with-display": { sku: "700513934", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-j129-ip-phone-no-power-supply": { sku: "700513638", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1-port-10gbase-sr-xfp-transceiver-dupe": { sku: "AA1403005-E5", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1000base-lx-sfp-network-transceiver-module-1000-mbit-s": { sku: "AA1419049-E6", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1120e-ip-phone-graphite-no-psu-dupe": { sku: "NTYS03AFE6-AVAYA", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1120sa-voip-phone-dupe": { sku: "1120SA", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1140e-ip-deskphone-dupe": { sku: "1140E", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1151b1-power-supply-dupe": { sku: "700227242", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1408-ip-phone-black-wired": { sku: "700469851", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1416-digital-phone-blk-dupe": { sku: "700509194", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1608-i-ip-deskphone-icon-only-700415557": { sku: "700508260", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1608ipphone-700415557": { sku: "700415557", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1616-i-ip-phone-black-16-lines": { sku: "700458540", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1616ipphone-700415565": { sku: "700415565", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-3735-ip-phone-black-lcd-700513192-dupe": { sku: "700513192", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-3745-ip-phone-black-lcd-700510284-dupe": { sku: "700510284", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-3901-headsets-dupe": { sku: "3901", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-3904-digital-deskphone-dupe": { sku: "3904", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-3905-digital-deskphone-dupe": { sku: "3905", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-4550t-with-48-10-100-basetx-dupe": { sku: "AL4500A02-E6", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-5520-48t-pwr-with-48-10-100-1000-dupe": { sku: "5520-48T-PWR", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-6416d-m-digital-telephone-dupe": { sku: "6416RF", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-700466253-mobile-device-charger-black-indoor": { sku: "700466253", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-700513569-j179-ip-phone-wired-handset-dupe": { sku: "700513569", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-700513905-vantage-k175-ip-phone-black-grey-wi-fi": { sku: "700513905", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-700513916-j139-ip-phone-wired-handset": { sku: "700513916", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-9611g-ip-phone": { sku: "700480593", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-9641-ip-phone-wired-handset-lcd-5-lines": { sku: "700503700", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b100-expansion-microphones-700501539-dupe": { sku: "700501539", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b109-conference-phone-dupe": { sku: "700514009", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b149-conference-phone-dupe": { sku: "700501533", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b159-conference-phone-dupe": { sku: "B159", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b169-wireless-conference-phone-dupe": { sku: "B169 SIP", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b169-ip-conference-phone": { sku: "700514483", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b169-wireless-conference-phone-dupe-2": { sku: "700508893", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b179-conference-voip-phone-dupe": { sku: "B179", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b179-conference-phone": { sku: "700501532", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b189-ip-conference-phone-dupe": { sku: "B189", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-b199-ip-conference-phone-700514246": { sku: "700514246", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-conference-phone-b199-dupe": { sku: "B199", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-cu360-huddle-room-device-700513892-new": { sku: "700513892", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-dect-3730-telephone-handset-caller-dupe": { sku: "700513191", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-ethernet-routing-switch-4526t-with": { sku: "AL4500A03-E6", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-global-sngl-pt-poe-injector-kit-dupe": { sku: "700512602", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-h175-video-collab-stn-dupe": { sku: "700508246", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-ip-phone-1616-i-blk-dupe": { sku: "700454843", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-ip-phone-9611g-icon-only-dupe": { sku: "700504845", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-j159-ip-phone-led-wi-fi-dupe": { sku: "700512394", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-j169-ip-phone-black-wired-handset-dupe": { sku: "700513634", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-j189-ip-phone-grey-led-wi-fi-700512396": { sku: "700512396", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-jem24-expansion-module-700514337-dupe": { sku: "700514337", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-l119-headset-quick-dupe": { sku: "L119", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-l129-headset-dupe": { sku: "700514052", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-l139-qd-mono-headset-dupe": { sku: "700514053", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-l149-headset-dupe": { sku: "700514054", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-l159-headset-dupe": { sku: "700514055", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-ntys03afe61120eipdeskphone": { sku: "NTYS03AFE6", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-room-system-xt4300-dupe": { sku: "XT4300", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-room-system-xt5000-dupe": { sku: "XT5000", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-room-system-xt7100-dupe": { sku: "XT7100", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-routing-switch-4524gt-pwr-switch-24-ports": { sku: "4524GT-PWR", category: "Avaya", price: "Get a Quote", availability: "" },
  "avaya-1603-ip-phone-700415540": { sku: "700415540", category: "Avaya", price: "Get a Quote", availability: "" },
  "nortel-ip-phone-1140e-ntys05": { sku: "NTYS05", category: "Avaya", price: "Get a Quote", availability: "" },
  "nortel-m3902-digital-phone-ntmn32": { sku: "NTMN32", category: "Avaya", price: "Get a Quote", availability: "" },
  "nortel-m3904-digital-phone-ntmn34": { sku: "NTMN34", category: "Avaya", price: "Get a Quote", availability: "" },
  "nortel-m3905-digital-phone-ntmn35": { sku: "NTMN35", category: "Avaya", price: "Get a Quote", availability: "" },
  "nortel-ntmn31-meridian-m3901-charcoal-single-line": { sku: "NTMN31", category: "Avaya", price: "Get a Quote", availability: "" },

  // --- Axis ---
  "axis-5801-352-network-switch": { sku: "5801-352", category: "Axis", price: "Get a Quote", availability: "" },

  // --- Microsoft ---
  "microsoft-surface-dock-mobile-device-pf3": { sku: "PF3-00005", category: "Docking Station, Microsoft, Microsoft Docking Station", price: "Get a Quote", availability: "" },

  // --- Hikvision ---
  "hikvision-6mp-ip-bullet-camera-ip66-h265-plus": { sku: "DS-2CD2666G2-IZS(2.8-12MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-deepinview-ds-2td2617b-6-pa-thermal-camera": { sku: "DS-2TD2617B-6/PA", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-cmos-varifocal-network-bullet-camera-ipc-b620-z": { sku: "IPC-B620-Z", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-acusense-motorized-varifocal-dome-2cd2747g2-lzs": { sku: "DS-2CD2747G2-LZS(3.6-9MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-cmos-motorized-turret-camera-ipc-t640-z": { sku: "IPC-T640-Z", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-acusense-ai-dome-network-camera": { sku: "DS-2CD2186G2-ISU(2.8MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-digital-technology-bullet-network-camera": { sku: "DS-2CD2T86G2-2I(4MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-acusense-bullet-network-camera-ds-2cd2t86g2-2i": { sku: "DS-2CD2T86G2-2I(2.8MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-acusense-motorized-varifocal-dome-ir-ds-2cd2746g2": { sku: "DS-2CD2746G2-IZS(2.8-12mm)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-turbo-hd-2mp-15x-ptz-camera-ds-2ae4215t-d3c": { sku: "DS-2AE4215T-D3(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-turbo-hd-2mp-25x-ptz-camera-ds-2ae5225ti-a-e": { sku: "DS-2AE5225TI-A(E)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-ip-mini-bullet-camera-ds-2cd2025fwd-i": { sku: "DS-2CD2025FWD-I(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-colorvu-ip-mini-bullet-ds-2cd2047g2-lu": { sku: "DS-2CD2047G2-LU(2.8MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-ip-fixed-dome-with-mic-ds-2cd2125g0-ims": { sku: "DS-2CD2125G0-IMS(2.8mm)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-fixed-dome-camera-ds-2cd2143g0-i": { sku: "DS-2CD2143G0-I(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-fixed-dome-wdr-ds-2cd2145fwd-i": { sku: "DS-2CD2145FWD-I(4mm)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-dome-camera-wdr-ds-2cd2145fwd-i-variant": { sku: "DS-2CD2145FWD-I(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-acusense-dome-with-audio-ds-2cd2146g2-isu": { sku: "DS-2CD2146G2-ISU(4MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-acusense-outdoor-dome-ds-2cd2146g2-isu-ip": { sku: "DS-2CD2146G2-ISU(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-6mp-ip-fixed-dome-camera-ds-2cd2163g0-i": { sku: "DS-2CD2163G0-I(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-ip-turret-camera-ds-2cd2323g0-i": { sku: "DS-2CD2323G0-I(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-darkfighter-turret-ds-2cd2346g1-i": { sku: "DS-2CD2346G1-I(2.8mm)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-colorvu-turret-camera-ds-2cd2347g1-lu": { sku: "DS-2CD2347G1-LU(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-turret-camera-colorvu-ds-2cd2347g1-lu-variant": { sku: "DS-2CD2347G1-LU(4MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-acusense-colorvu-turret-ds-2cd2347g2-lu": { sku: "DS-2CD2347G2-LU(2.8mm)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-ip-turret-camera-ds-2cd2383g0-i": { sku: "DS-2CD2383G0-I(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-acusense-color-siren-turret-ds-2cd2386g2": { sku: "DS-2CD2386G2-ISU/SL(2.8MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-acusense-turret-builtin-mic-ds-2cd2386g2-iu": { sku: "DS-2CD2386G2-IU(2.8mm)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-acusense-color-strobe-light-turret-ds-2cd2387g2p": { sku: "DS-2CD2387G2P-LSU/SL(4MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-motorized-varifocal-bullet-ds-2cd2623g0-izs": { sku: "DS-2CD2623G0-IZS(2.8-12MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-varifocal-bullet-ds-2cd2645fwd-izs": { sku: "DS-2CD2645FWD-IZS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-acusense-motorized-bullet-ds-2cd2686g2": { sku: "DS-2CD2686G2-IZS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-varifocal-dome-ds-2cd2745fwd-izs": { sku: "DS-2CD2745FWD-IZS(2.8-12MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-acusense-motorized-dome-ds-2cd2786g2": { sku: "DS-2CD2786G2-IZS(2.8-12MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-exir-fixed-bullet-ds-2cd2t43g0-i5": { sku: "DS-2CD2T43G0-I5(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-colorvu-acusense-fixed-bullet-ds-2cd2t47g2-l": { sku: "DS-2CD2T47G2-L(4MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-colorvu-fixed-bullet-ds-2cd2t87g2-l": { sku: "DS-2CD2T87G2-L(4MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-180-degree-pano-multi-sensor-camera-ds-2cd6924f-is": { sku: "DS-2CD6924F-IS(4mm)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-5mp-turbo-hd-fixed-dome-ds-2ce56h0t-it3e": { sku: "DS-2CE56H0T-IT3E(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-5mp-turbo-hd-mini-dome-ds-2ce56h0t-itme": { sku: "DS-2CE56H0T-ITME(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-25x-optical-zoom-ip-ptz-dome-ds-2de5425iw-ae": { sku: "DS-2DE5425IW-AE(T5)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-25x-optical-zoom-ip-ptz-dome-ds-2de7225iw-ae": { sku: "DS-2DE7225IW-AE", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-darkfighter-25x-ip-ptz-ds-2df6225x-ael": { sku: "DS-2DF6225X-AEL", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-bi-spectrum-thermal-bullet-ds-2td2617-3-v1": { sku: "DS-2TD2617-3/V1", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-thermal-and-optical-bi-spectrum-bullet-ds-2td2636b-15-p": { sku: "DS-2TD2636B-15/P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8-port-poe-plus-unmanaged-network-switch-ds-3e0310hp-e": { sku: "DS-3E0310HP-E", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4-channel-turbo-hd-dvr-poe-over-coax-ds-7204huhi-k1-p": { sku: "DS-7204HUHI-K1/P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8-channel-turbo-hd-dvr-poe-over-coax-ds-7208hqhi-k2-p": { sku: "DS-7208HQHI-K2/P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-turbo-hd-dvr-poe-over-coax-ds-7216huhi-k2-p": { sku: "DS-7216HUHI-K2/P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8-channel-4k-nvr-with-8-port-poe-ds-7608ni-k1-8p": { sku: "DS-7608NI-K1/8P(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-4k-nvr-with-16-poe-ports-ds-7616ni-i2-16p": { sku: "DS-7616NI-I2/16P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-32-channel-4k-nvr-4-sata-ds-7732ni-i4-kb-cvbs": { sku: "DS-7732NI-I4/KB/CVBS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-7-inch-touchscreen-wifi-video-intercom-indoor-station-ds-kh6320-wte1": { sku: "DS-KH6320-WTE1", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-video-intercom-kit-poe-ds-kis603-p": { sku: "DS-KIS603-P(B)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-video-intercom-system-accessory-ds-kis603-p-variant": { sku: "DS-KIS603-P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-turbo-hd-2mp-15x-optical-zoom-ptz-camera-ds-2ae4215t-d3c": { sku: "DS-2AE4215T-D3", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-6mp-ip-fixed-bullet-camera-ds-2cd2065g1-i": { sku: "DS-2CD2065G1-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-ip-fixed-dome-camera-ds-2cd2123g0-i": { sku: "DS-2CD2123G0-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-fixed-dome-audio-alarm-ds-2cd2143g0-is": { sku: "DS-2CD2143G0-IS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-fixed-dome-120db-wdr-ds-2cd2145fwd-i": { sku: "DS-2CD2145FWD-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-6mp-ip-fixed-dome-camera-ds-2cd2163g0-ii": { sku: "DS-2CD2163G0-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-ip-fixed-dome-camera-ds-2cd2183g0-i": { sku: "DS-2CD2183G0-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-fixed-turret-wdr-ds-2cd2345fwd-i": { sku: "DS-2CD2345FWD-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-darkfighter-ip-turret-ds-2cd2346g1-i": { sku: "DS-2CD2346G1-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-acusense-audio-turret-ds-2cd2346g2-iu": { sku: "DS-2CD2346G2-IU(2.8MM)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-ip-colorvu-turret-camera-ds-2cd2347g1-lu": { sku: "DS-2CD2347G1-LU", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-5mp-ip-fixed-turret-wdr-ds-2cd2355fwd-ib": { sku: "DS-2CD2355FWD-I/B", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-6mp-ip-fixed-turret-camera-ds-2cd2363g0-i": { sku: "DS-2CD2363G0-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-6mp-darkfighter-ip-turret-ds-2cd2365g1-i": { sku: "DS-2CD2365G1-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-darkfighter-turret-ds-2cd2385g1-i": { sku: "DS-2CD2385G1-I", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-1-3mp-ip-mini-dome-audio-alarm-ds-2cd2512f-is": { sku: "DS-2CD2512F-IS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-acusense-motorized-varifocal-bullet-ds-2cd2646g2-izs": { sku: "DS-2CD2646G2-IZS(2.8-12mm)(C)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-motorized-varifocal-dome-wdr-ds-2cd2745fwd-izs": { sku: "DS-2CD2745FWD-IZS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-motorized-varifocal-dome-ds-2cd2785g0-izs": { sku: "DS-2CD2785G0-IZS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-motorized-varifocal-turret-wdr-ds-2cd2h45fwd-izs": { sku: "DS-2CD2H45FWD-IZS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4mp-long-range-ir-bullet-ds-2cd2t43g0-i5": { sku: "DS-2CD2T43G0-I5", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-6mp-long-range-ir-bullet-ds-2cd2t63g0-i5": { sku: "DS-2CD2T63G0-I5", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16mp-pano-vu-multi-sensor-camera-ds-2cd6924f-is": { sku: "DS-2CD6924F-IS", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-turbo-hd-motorized-varifocal-bullet-ds-2ce16d8t-it3ze": { sku: "DS-2CE16D8T-IT3ZE", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8mp-4k-turbo-hd-box-camera-ds-2ce37u8t-a": { sku: "DS-2CE37U8T-A", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-3k-5mp-turbo-hd-colorvu-turret-ds-2ce72kf3t-le": { sku: "DS-2CE72KF3T-LE(2.8MM)", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-2mp-25x-optical-zoom-ip-ptz-ds-2de5225w-ae": { sku: "DS-2DE5225W-AE", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-3mp-30x-optical-zoom-ip-ptz-ds-2de5330w-ae": { sku: "DS-2DE5330W-AE", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-bi-spectrum-thermal-bullet-ds-2td2628-3-qa": { sku: "DS-2TD2628-3/QA", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8-port-100mbps-unmanaged-poe-switch-ds-3e0109p-e-c": { sku: "DS-3E0109P-E", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-port-managed-gigabit-poe-switch-ds-3e1318p-e": { sku: "DS-3E1318P-E", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-24-port-managed-gigabit-poe-switch-ds-3e1326p-e": { sku: "DS-3E1326P-E", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-turbo-hd-dvr-4-sata-ds-7316hqhi-k4": { sku: "DS-7316HQHI-K4", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-4-channel-4k-nvr-ds-7604ni-k1": { sku: "DS-7604NI-K1", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8-channel-4k-nvr-ds-7608ni-k2": { sku: "DS-7608NI-K2", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8-channel-4k-nvr-with-8-poe-ds-7608ni-m2-8p": { sku: "DS-7608NI-M2/8P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-4k-nvr-2-sata-i-series-ds-7616ni-i2": { sku: "DS-7616NI-I2", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-4k-nvr-ds-7616ni-k2": { sku: "DS-7616NI-K2", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-4k-nvr-with-16-poe-ds-7616ni-m2-16p": { sku: "DS-7616NI-M2/16P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-32-channel-4k-nvr-2-sata-i-series-ds-7632ni-i2": { sku: "DS-7632NI-I2", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-4k-nvr-4-sata-ds-7716ni-k4": { sku: "DS-7716NI-K4", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-32-channel-4k-nvr-4-sata-ds-7732ni-k4": { sku: "DS-7732NI-K4", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-32-channel-4k-nvr-16-poe-ds-7732ni-m4-16p": { sku: "DS-7732NI-M4/16P", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-64-channel-enterprise-4k-nvr-8-sata-ds-9664ni-m8": { sku: "DS-9664NI-M8", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-21-5-inch-full-hd-surveillance-monitor-ds-d5022fn-c": { sku: "DS-D5022FN-C", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-fingerprint-mifare-access-control-reader-ds-k1201mf": { sku: "DS-K1201MF", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-outdoor-pro-access-control-terminal-ds-k1t500s": { sku: "DS-K1T500S", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-basic-pro-access-control-terminal-ds-k1t501sf": { sku: "DS-K1T501SF", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-standalone-em-card-fingerprint-terminal-ds-k1t804ef-1": { sku: "DS-K1T804EF-1", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-standalone-mifare-fingerprint-terminal-ds-k1t804mf-1": { sku: "DS-K1T804MF-1", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-7-inch-analogue-video-intercom-kit-ds-kis203": { sku: "DS-KIS203", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-8-channel-acusense-turbo-hd-dvr-ds-7208hqhi-k1-4s": { sku: "iDS-7208HQHI-K1/4S", category: "Hikvision", price: "Get a Quote", availability: "" },
  "hikvision-16-channel-acusense-turbo-hd-dvr-ds-7316hqhi-m4-s": { sku: "IDS-7316HQHI-M4/S", category: "Hikvision", price: "Get a Quote", availability: "" },

  // --- MISSING BEST SELLERS ---
  "acer-v246hl-24-1920-x-1080-pixels-full-hd-led-black": { sku: "", category: "Acer", price: "Get a Quote", availability: "" },
  "acer-v227qbip-full-hd-21-5-ips-lcd-monitor-black": { sku: "", category: "Acer", price: "Get a Quote", availability: "" },
  "lexmark-62d2h0e-622h-toner-black-25k-pages": { sku: "", category: "Lexmark", price: "Get a Quote", availability: "" },
  "aruba-jl683a-aba-instant-on-1930": { sku: "", category: "Aruba", price: "Get a Quote", availability: "" },
  "hpe-aruba-ap-303p-us": { sku: "", category: "HPE", price: "Get a Quote", availability: "" },
  "apc-netshelter-sx-24u-freestanding-rack-black": { sku: "", category: "APC, UPS", price: "Get a Quote", availability: "" },
  "apc-netshelter-sx-48u-600mm-wide-x-1070mm": { sku: "", category: "APC, UPS", price: "Get a Quote", availability: "" },
  "apc-easy-ups-line-interactive": { sku: "", category: "APC, UPS", price: "Get a Quote", availability: "" },
  "ubiquiti-u6-pro-unifi-wifi-6-access-point": { sku: "", category: "Ubiquiti", price: "Get a Quote", availability: "" },
  "msi-cyborg-15-ai-a1vfk-001uk": { sku: "", category: "MSI", price: "Get a Quote", availability: "" },
  "msi-pro-h610m-e-motherboard-intel-h610-lga-1700-micro-atx": { sku: "", category: "MSI", price: "Get a Quote", availability: "" },
  "ubiquiti-unifi-cloud-gateway-max-ucg-max-512gb": { sku: "", category: "Ubiquiti Router", price: "Get a Quote", availability: "" },
  "alcatel-lucent-network-transceiver-module-sfp-10g-lr": { sku: "", category: "Cisco, Cisco SFP Module", price: "Get a Quote", availability: "" },
  "epson-c13s0506910691-toner-kit-black-return-program-10k-pages-for-epson-workforce-al-m-300": { sku: "", category: "Epson", price: "Get a Quote", availability: "" },
  "acer-predator-ph18-72-intel-core-i9": { sku: "", category: "Acer", price: "Get a Quote", availability: "" },

  // --- MISSING RECENTLY ADDED ---
  "lenovo-thinkbook-16-g6-irl-16-inch-laptop-with-intel-core-i5-8gb-ram-256gb-ssd-and-1920x1200-display": { sku: "21KH0009UK", category: "Lenovo Laptop", price: "Get a Quote", availability: "" },

};